controllers:
    resource: '../../src/Jason/CoreBundle/Presentation/Controller/'
    type: attribute
    
when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
